import tequila as tq
import sunrise as sun
from pyscf import scf
from pyscf.tools import molden
from time import time
import subprocess

geo = '''
    C	0.0000000	1.3894860	0.0000000
    C	1.2033300	0.6947430	0.0000000
    C	1.2033300	-0.6947430	0.0000000
    C	0.0000000	-1.3894860	0.0000000
    C	-1.2033300	-0.6947430	0.0000000
    C	-1.2033300	0.6947430	0.0000000
    H	0.0000000	2.4702840	0.0000000
    H	2.1393290	1.2351420	0.0000000
    H	2.1393290	-1.2351420	0.0000000
    H	0.0000000	-2.4702840	0.0000000
    H	-2.1393290	-1.2351420	0.0000000
    H	-2.1393290	1.2351420	0.0000000'''
basis = 'sto-3g'
threshold = 1.e-9
begining = time()
mol = tq.Molecule(geometry=geo,basis_set=basis)
pfmol = sun.from_tequila(mol)
mf = scf.RHF(pfmol).run()
name = mol.parameters.name
with open(f'{name}.molden', 'w') as f1:
    molden.header(pfmol, f1)
    molden.orbital_coeff(pfmol, f1, mf.mo_coeff, ene=mf.mo_energy, occ=mf.mo_occ)

#TODO: Not really sure when to use each version of pyscf molden generation
# try:
#     molden.from_mo(pfmol, f'{mol.parameters.name}_pyscf.molden', mf.mo_coeff)
# except RuntimeError:
#     print('    Found l=5 in basis.')
#     molden.from_mo(pfmol, f'{mol.parameters.name}_pyscf.molden', mf.mo_coeff, ignore_h=True)
# #Pyscf tutorial Molden: https://github.com/pyscf/pyscf/blob/master/examples/tools/02-molden.py


#it will give you some options, accept only the first: Do you want to generate a new Molden file? ([Yes] / No)
subprocess.call(['./molden2aim.exe', '-i', f'{name}.molden'])
subprocess.call(['rm','m2a.ini']) #rm molden2aim input file autogenerated
subprocess.call(['java', '-jar', 'molden2molden.jar','-cart2pure','-normalizebf','-i',f'{name}_new.molden','-o',f'{name}.PURE'])
subprocess.call(['java', '-jar', 'JANPA.jar','-i',f'{name}.PURE','-CLPO_Molden_File',f'{name}_CLPO.molden','-HybrOptOccConvThresh',f'{threshold}'])
subprocess.call(['./replace.sh', f'{name}_CLPO.molden']) #if it doesnt work here: chmod u+rx replace.sh and run it again

fmol, mo_energy, mo_coeff, mo_occ, irrep_labels, spins = molden.load(f'{name}_CLPO.molden')
mol = sun.MoleculeFromPyscf(molecule=fmol,mo_coeff=mo_coeff,basis_set=basis)
print(f'Overall Time {time()-begining} s')
# sun.plot_MO(mol,filename=f'{name}_CLPO')

#TODO: it considers and does nothing about the frozen orbital, maybe we should do something with it