import tequila as tq
from tequila.quantumchemistry.qc_base import QuantumChemistryBase
import numpy
import sunrise as sun
from pyscf import scf
from pyscf.tools import molden
from time import time
import subprocess
from copy import deepcopy


def transform(original:QuantumChemistryBase,janpa:QuantumChemistryBase)->QuantumChemistryBase:
    def inner(a, b, s):
        return numpy.sum(numpy.multiply(numpy.outer(a, b), s))
    core = [i.idx_total for i in original.integral_manager.orbitals if i.idx is None]

    assert len(original.integral_manager.orbitals) == len(janpa.integral_manager.orbitals)
    n_basis = len(original.integral_manager.orbitals)
    ov = numpy.zeros(shape=(n_basis))
    for i in core:
        for j in range(n_basis):
            ov[j] += numpy.abs(inner(original.integral_manager.orbital_coefficients.T[i], janpa.integral_manager.orbital_coefficients.T[j], original.integral_manager.overlap_integrals))
    co = []
    for _ in core:
        idx = numpy.argmax(ov)
        co.append(idx)
        ov[idx] = 0
    co.sort()
    active = [i for i in range(len(original.integral_manager.orbitals)) if  i not in co]
    reference_orbitals = []
    i =0
    while len(reference_orbitals)<original.parameters.total_n_electrons//2-len(core):
        if i not in co:
            reference_orbitals.append(i)
        i += 1
    integral_manager = janpa.initialize_integral_manager(one_body_integrals=original.integral_manager.one_body_integrals,
                    two_body_integrals=original.integral_manager.two_body_integrals,constant_term=original.integral_manager.constant_term,
                    active_orbitals=active,frozen_orbitals=co,orbital_coefficients=janpa.integral_manager.orbital_coefficients,
                    overlap_integrals=original.integral_manager.overlap_integrals,reference_orbitals=reference_orbitals + co)
    parameters = deepcopy(original.parameters)
    return QuantumChemistryBase(parameters=parameters,integral_manager=integral_manager,transformation=original.transformation)


geo = '''
    C	0.0000000	1.3894860	0.0000000
    C	1.2033300	0.6947430	0.0000000
    C	1.2033300	-0.6947430	0.0000000
    C	0.0000000	-1.3894860	0.0000000
    C	-1.2033300	-0.6947430	0.0000000
    C	-1.2033300	0.6947430	0.0000000
    H	0.0000000	2.4702840	0.0000000
    H	2.1393290	1.2351420	0.0000000
    H	2.1393290	-1.2351420	0.0000000
    H	0.0000000	-2.4702840	0.0000000
    H	-2.1393290	-1.2351420	0.0000000
    H	-2.1393290	1.2351420	0.0000000'''
basis = 'sto-3g'
threshold = 1.e-9
begining = time()
mol = tq.Molecule(geometry=geo,basis_set=basis)
pfmol = sun.from_tequila(mol)
mf = scf.RHF(pfmol).run()
name = mol.parameters.name 
#IDEA: Not really sure when to use each version of pyscf molden generation
### OPTION 1
with open(f'{name}.molden', 'w') as f1:
    molden.header(pfmol, f1)
    molden.orbital_coeff(pfmol, f1, mf.mo_coeff, ene=mf.mo_energy, occ=mf.mo_occ)
### OPTION 2
# try:
#     molden.from_mo(pfmol, f'{mol.parameters.name}.molden', mf.mo_coeff)
# except RuntimeError:
#     print('    Found l=5 in basis.')
#     molden.from_mo(pfmol, f'{mol.parameters.name}.molden', mf.mo_coeff, ignore_h=True)
# #Pyscf tutorial Molden: https://github.com/pyscf/pyscf/blob/master/examples/tools/02-molden.py


#it will give you some options, accept only the first: Do you want to generate a new Molden file? ([Yes] / No)
subprocess.call(f'./molden2aim.exe -i {name}.molden',shell=True)
subprocess.call(f'java -jar molden2molden.jar -cart2pure -normalizebf -i {name}_new.molden -o {name}.PURE',shell=True)
subprocess.call(f'java -jar JANPA.jar -i {name}.PURE -CLPO_Molden_File {name}_CLPO.molden -HybrOptOccConvThresh {threshold}',shell=True)
subprocess.call(f'./replace.sh {name}_CLPO.molden',shell=True) #if it doesnt work here: chmod u+rx replace.sh and run it again
subprocess.call(f'rm m2a.ini',shell=True) #rm molden2aim input file autogenerated
subprocess.call(f'rm {name}.PURE',shell=True) 
subprocess.call(f'rm {name}.molden',shell=True) 
subprocess.call(f'rm {name}_new.molden',shell=True) 

fmol, mo_energy, mo_coeff, mo_occ, irrep_labels, spins = molden.load(f'{name}_CLPO.molden')
mol = transform(mol,sun.MoleculeFromPyscf(molecule=fmol,mo_coeff=mo_coeff,basis_set=basis))
print(f'Overall Time {time()-begining} s')
sun.plot_MO(mol,filename=f'{name}_CLPO')

# JANPA orders the orbitals by bonding-antibonding pairs, therefore the edges will be:
edges = [(2*i,2*i+1) for i in range(mol.n_electrons//2)]